version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.23.3
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api/tmp:/api/tmp
      - ./api/public:/api/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - front

  api:
    container_name: api
    build:
      context: ./api
    ports:
      - "3001:3000"
    depends_on:
      - db
    volumes:
      - ./api:/app/
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails server -b '0.0.0.0'"

  front:
    container_name: front
    build:
      context: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app/
    command: bash -c "npm install && npm run dev"

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - /etc/letsencrypt:/etc/letsencrypt
  #     - /var/lib/letsencrypt:/var/lib/letsencrypt
  #   command: certonly --webroot --webroot-path=./certbot/test.txt -d example.com

  db:
    container_name: db
    image: postgres:15.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_development
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
